function [BW_f] = segmentation_colorbased_2023(RGB)
%createMask  Threshold RGB image using auto-generated code from colorThresholder app.
%  [BW,MASKEDRGBIMAGE] = createMask(RGB) thresholds image RGB using
%  auto-generated code from the colorThresholder app. The colorspace and
%  range for each channel of the colorspace were set within the app. The
%  segmentation mask is returned in BW, and a composite of the mask and
%  original RGB images is returned in maskedRGBImage.

% Auto-generated by colorThresholder app on 15-Dec-2023
%------------------------------------------------------


% Convert RGB image to chosen color space
I = rgb2hsv(RGB);

% Define thresholds for channel 1 based on histogram settings
channel1Min = 0.729;
channel1Max = 0.604;

% Define thresholds for channel 2 based on histogram settings
channel2Min = 0.000;
channel2Max = 0.361;

% Define thresholds for channel 3 based on histogram settings
channel3Min = 0.000;
channel3Max = 0.891;

% Create mask based on chosen histogram thresholds
sliderBW = ( (I(:,:,1) >= channel1Min) | (I(:,:,1) <= channel1Max) ) & ...
    (I(:,:,2) >= channel2Min ) & (I(:,:,2) <= channel2Max) & ...
    (I(:,:,3) >= channel3Min ) & (I(:,:,3) <= channel3Max);
BW = sliderBW;

% Invert mask
BW = ~BW;

% Dilate the image to smoothen the roughness in the image
se=strel('disk',2);
BW=imdilate(BW,se);
% get biggest components
BW_f = bwareafilt(BW, 1, 'Largest');

end
